asp-vet/Controllers/AtendimentoController.cs
using asp_vet.Dados;
using asp_vet.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace asp_vet.Controllers
{
    public class AtendimentoController : Controller
    {
        public void CarregaVet()
        {
            List<SelectListItem> vet = new List<SelectListItem>();
            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdVeterinaria;User=root;pwd=Figure.09"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("Select * from tbveterinario order by nomevet;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    vet.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

            }
            ViewBag.vet = new SelectList(vet, "Value", "Text");

        }

        public void CarregaAnimal()
        {
            List<SelectListItem> animal = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdVeterinaria;User=root;pwd=Figure.09"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbAnimal order by NomeAnimal;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    animal.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

            }
            ViewBag.animal = new SelectList(animal, "Value", "Text");
        }
            AcoesAtendimento acAtend = new AcoesAtendimento();

        public ActionResult CadAtendimento() // abre a tela
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                CarregaAnimal();
                CarregaVet();

            }
            return View();
        }

        [HttpPost]
        public ActionResult CadAtendimento(ModelAtendimento cmAtend) // cadastra no banco
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1") 
            {
                CarregaAnimal();
                CarregaVet();
                acAtend.TestarAgenda(cmAtend);

            if (cmAtend.confAgendamento == "0")
            {
                ViewBag.msg = "Horário Indisponível! Tente outro.";
            }
            else
            {
                    CarregaAnimal();
                    CarregaVet();
                    cmAtend.codVet = Request["veterinario"];
                cmAtend.codAnimal = Request["animal"];
                acAtend.InserirAtendimento(cmAtend);
                ViewBag.msg = "Cadastro Realizado com sucesso!";
            }

            }
            else
            {
                return RedirectToAction("SemAcesso", "Home");
            }
            return View();
        }
    }
}

asp-vet/Controllers/HomeController.cs
using MySql.Data.MySqlClient;
using asp_vet.Dados;
using asp_vet.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace asp_vet.Controllers
{
    public class HomeController : Controller
    {
        AcoesLogin acL = new AcoesLogin();
        AcoesUser acTipo = new AcoesUser();

        public void carregaTipoUsu()
        {
            List<SelectListItem> tipoUsu = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdVeterinaria;User=root;pwd=Figure.09"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbTipoUsuario;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    tipoUsu.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

            }
            ViewBag.tipoUsu = new SelectList(tipoUsu, "Value", "Text");
        }

        public void carregaLogin()
        {
            List<SelectListItem> login = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdVeterinaria;User=root;pwd=Figure.09"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbLogin;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    login.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

            }
            ViewBag.login = new SelectList(login, "Value", "Text");
        }

        public ActionResult Index()
        {
            Session["tipo"] = "";
            return View();
        }

        [HttpPost]
        public ActionResult Index(ModelLogin cm)
        {
            acL.TestarUsuario(cm);

            if (cm.usuario != null)
            {
                FormsAuthentication.SetAuthCookie(cm.usuario, false);
                Session["usu"] = cm.usuario;
                Session["tipo"] = cm.codTipoUsuario;

                if (Session["usu"] != null && Session["tipo"].ToString() == "1")
                {
                    return RedirectToAction("MenuAdm", "Home");
                }
                else if (Session["usu"] != null && Session["tipo"].ToString() == "2")
                {
                    return RedirectToAction("MenuUser", "Home");

                }
                else
                {
                    ViewBag.msgLogar = "Usuário e/ou senha incorreto(s)";
                    return View();

                }
               
            }

            else
            {
                ViewBag.msgLogar = "Usuário e/ou senha incorreto(s)";
                return View();
            }
        }

        public ActionResult SemAcesso()
        {
            Response.Write("<script>alert('Sem Acesso - Faça o login no sistema')</script>");
            return View();
        }

        public ActionResult Logout()
        {
            Session["usu"] = null;
            Session["tipo"] = null;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult CadTipo()
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                return View();
            }
            else
            {

                return RedirectToAction("SemAcesso", "Home");
            }
        }

        [HttpPost]
        public ActionResult CadTipo(ModelUser cmTipo)
        {
            acTipo.inserirTipo(cmTipo);
            ViewBag.msgCad = "Cadastro Efetuado";
            return View();
        }

        public ActionResult ConsCadTipo()
        {
            if (Session["usu"] != null)
            {
                GridView dgv = new GridView();
                dgv.DataSource = acTipo.consultaTipo();
                dgv.DataBind();
                StringWriter sw = new StringWriter();
                HtmlTextWriter htw = new HtmlTextWriter(sw);
                dgv.RenderControl(htw);
                ViewBag.GridViewString = sw.ToString();
                return View();
            }
            else
            {
                return RedirectToAction("SemAcesso", "Home");
            }
        }

        public ActionResult CadLogin()
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                carregaTipoUsu();
                return View();
            }
            else
            {

                return RedirectToAction("SemAcesso", "Home");
            }
        }
        [HttpPost]
        public ActionResult CadLogin(ModelLogin cmLogin)
        {
            carregaTipoUsu();
            if (cmLogin.senha == cmLogin.confirmaSenha)
            {

                cmLogin.codTipoUsuario = Request["tipoUsu"];
                acL.inserirLogin(cmLogin);
                Response.Write("<script>alert('Cadastro efetuado com sucesso!')</script>");
            }
            else
            {
                Response.Write("<script>alert('As senhas não estão iguais.')</script>");
            }
            return View();
        }

        public ActionResult MenuAdm()
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                return View();
            }
            else
            {

                return RedirectToAction("SemAcesso", "Home");
            }


        }
        public ActionResult MenuUser()
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "2")
            {
                return View();
            }
            else
            {

                return RedirectToAction("SemAcesso", "Home");
            }


        }
    }

    
}

asp-vet/Controllers/TipoAnimalController.cs
using asp_vet.Dados;
using asp_vet.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace asp_vet.Controllers
{
    public class TipoAnimalController : Controller
    {
        AcoesTipoAnimal aTP = new AcoesTipoAnimal();


       public void CarregaTipoAnimal() 
        {

            List<SelectListItem> tipoAnimal = new List<SelectListItem>();
            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdVeterinaria;User=root;pwd=Figure.09")) 
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from TipoAnimal;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    tipoAnimal.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });

                }
                con.Close();
            }
            ViewBag.tipoAnimal = new SelectList(tipoAnimal, "Value", "Text");
        }

        public ActionResult CadTipoAnimal() 
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                return View();
            }
            else
            {

                return RedirectToAction("SemAcesso", "Home");
            }
        }

        [HttpPost]
        public ActionResult CadTipoAnimal(ModelTipoAnimal cmTipoAnimal)
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                CarregaTipoAnimal();
                cmTipoAnimal.codTipoAnimal = Request["CodTipoAnimal"];
                aTP.InserirTipoAnimal(cmTipoAnimal);
                ViewBag.msgCad = "Cadastro efetuado com sucesso!";
                return View();
            }
            else
            {

                return RedirectToAction("SemAcesso", "Home");
            }
        }

        public ActionResult ConsTipoAnimal()
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                GridView dgv = new GridView();
                dgv.DataSource = aTP.ConsultarTipoAnimal();
                dgv.DataBind();
                StringWriter sw = new StringWriter();
                HtmlTextWriter htw = new HtmlTextWriter(sw);
                dgv.RenderControl(htw);
                ViewBag.GridViewString = sw.ToString();
                return View();
            }
            else
            {
                return RedirectToAction("SemAcesso", "Home");
            }
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

asp-vet/Controllers/VeterinarioController.cs
using asp_vet.Dados;
using asp_vet.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace asp_vet.Controllers
{
    public class VeterinarioController : Controller
    {
        AcoesVeterinario av = new AcoesVeterinario();

        public void CarregaVet()
        {
            List<SelectListItem> vet = new List<SelectListItem>();
            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdVeterinaria;User=root;pwd=Figure.09"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("Select * from tbveterinario order by nomevet;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    vet.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

            }
            ViewBag.vet = new SelectList(vet, "Value", "Text");

        }

        public ActionResult CadVet()
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                return View();
            }
            else
            {

                return RedirectToAction("SemAcesso", "Home");
            }

        }
        [HttpPost]

        public ActionResult CadVet(ModelVeterinario cmVet) 
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                CarregaVet();
                cmVet.codVet = Request["CodVet"];
                av.InserirVeterinario(cmVet);
                ViewBag.msgCad = "Cadastro realizado com sucesso!";
                return View();
            }
            else
            {

                return RedirectToAction("SemAcesso", "Home");
            }
        }

        public ActionResult ConsVet()
        {
            if (Session["usu"] != null)
            {
                GridView dgv = new GridView();
                dgv.DataSource = av.ConsultarVeterinario();
                dgv.DataBind();
                StringWriter sw = new StringWriter();
                HtmlTextWriter htw = new HtmlTextWriter(sw);
                dgv.RenderControl(htw);
                ViewBag.GridViewString = sw.ToString();
                return View();
            }
            else
            {
                return RedirectToAction("SemAcesso", "Home");
            }
        }
        // GET: Veterinario
        public ActionResult Index()
        {
            return View();
        }
    }
}

asp-vet/Views/Home/CadLogin.cshtml
@{
    ViewBag.Title = "CadLogin";
}

<h2>CadLogin</h2>

asp-vet/Views/Home/CadTipo.cshtml
@model asp_vet.Models.ModelUser
@{
    ViewBag.Title = "CadTipo";
}

<h2>Cadastro de Tipo de Usuário</h2>
@using (Html.BeginForm("CadTipo", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.LabelFor(m => m.usuario)
    <br />
    @Html.EditorFor(m => m.usuario)
    <br />
    <br />
    <input type="submit" value="Cadastrar" />
}

@ViewBag.msgCad

asp-vet/Views/Home/ConsCadTipo.cshtml
@{
    ViewBag.Title = "ConsCadTipo";
}

<h2>Consulta de Tipo de Usuário</h2>

@Html.Raw(ViewBag.GridViewString)

asp-vet/Views/Home/Index.cshtml
@model asp_vet.Models.ModelLogin
@{
    ViewBag.Title = "Home Page";
}

@ViewBag.confCadastro
@ViewBag.msgLogar

@using (Html.BeginForm("Index", "Home", FormMethod.Post))
{
    <fieldset>
        <br />
        <h2>Entrar</h2>
        <br />
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i style="font-size:20px;" class="fas fa-envelope"></i></span>

                @Html.EditorFor(x => x.usuario, new
           {
               htmlAttributes = new { id = "txtUsuario", senha = "txtUsuario", type = "text", @class = "form-control", placeholder = "Digite o usuario", required = "required", maxlength = "30" }
           })

                @Html.ValidationMessageFor(x => x.usuario, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i style="font-size:20px;" class="fas fa-lock"></i></span>

                @Html.EditorFor(x => x.senha, new
           {
               htmlAttributes = new { id = "txtSenha", senha = "txtSenha", type = "password", @class = "form-control", placeholder = "Digite sua senha", required = "required", maxlength = "10" }
           })

                @Html.ValidationMessageFor(x => x.senha, "", new { @class = "text-danger" })

            </div>
        </div>

        <input type="submit" class="button button-a button-big button-rouded" value="ENTRAR"><br />
        <br />

    </fieldset>
}

asp-vet/Views/Home/MenuAdm.cshtml
@{
    ViewBag.Title = "MenuAdm";
}

<link rel="stylesheet" href="~/Views/Home/Menus.css" />
<h2>Menu - Administrador</h2>

<h2>Bem-vindo(a)!</h2>

<section>
    <h2>Cadastrar</h2>
    <ul>
        <li> @Html.ActionLink("Animal", "CadAnimal", "Animal")</li>
        <li> @Html.ActionLink("Cliente", "CadCliente", "Cliente")</li>
        <li> @Html.ActionLink("Login", "CadLogin", "Home")</li>
        <li> @Html.ActionLink("Tipo de Animal", "CadTipoAnimal", "TipoAnimal")</li>
        <li> @Html.ActionLink("Veterinário", "CadVet", "Veterinario")</li>
    </ul>
    <h2>Consultar</h2>
    <ul>
        <li> @Html.ActionLink("Animal", "ConsAnimal", "Animal")</li>
        <li> @Html.ActionLink("Cliente", "ConsCliente", "Cliente")</li>
        <li> @Html.ActionLink("Login", "ConsLogin", "Home")</li>
        <li> @Html.ActionLink("Tipo de Animal", "ConsTipoAnimal", "TipoAnimal")</li>
        <li> @Html.ActionLink("Veterinário", "ConsVet", "Veterinario")</li>
    </ul>

    <h2>Agendamentos</h2>
    <ul>
        <li>Consultar</li>
        <li>@Html.ActionLink("Novo Atendimento", "CadAtendimento", "Atendimento")</li>
    </ul>
</section>

asp-vet/Views/Home/MenuUser.cshtml
@{
    ViewBag.Title = "Usuário";
}

<h2>Menu - Usuário</h2>
<h2>Consultar</h2>
<ul>
    <li> @Html.ActionLink("Animal", "ConsAnimal", "Animal")</li>
    <li> @Html.ActionLink("Cliente", "ConsCliente", "Cliente")</li>
    <li> @Html.ActionLink("Tipo de Animal", "ConsTipoAnimal", "TipoAnimal")</li>
    <li> @Html.ActionLink("Veterinário", "ConsVet", "Veterinario")</li>
</ul>

asp-vet/Views/Home/SemAcesso.cshtml
@{
    ViewBag.Title = "SemAcesso";
}
<h2>Ops!</h2>
<p>É preciso fazer login para acessar essa página. Volte ao início!</p>